mod tokens;
mod lexer;
mod ast;
mod parser;
mod compiler;
mod vm;

use std::fs;
use std::path::Path;
use clap::{Parser as CliParser, Subcommand};

use lexer::Lexer;
use parser::Parser;
use compiler::Compiler;
use vm::VM;

/// Command-Line interface definition for the .sa Compiler
#[derive(CliParser)]
#[command(name = "sac")]
#[command(about = "Compiler and VM for the .sa language", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Compiles the .sa file and previews the generated bytecode
    Compile {
        /// Path to the .sa source file
        file: String,
    },
    /// Runs the .sa file directly on the VM
    Run {
        /// Path to the .sa source file
        file: String,
    },
}

fn main() {
    let cli = Cli::parse();

    match &cli.command {
        Commands::Compile { file } => {
            let source = read_sa_file(file);
            let bytecode = compile_source(&source);
            
            println!("--- Bytecode Preview for {} ---", file);
            for (ip, instr) in bytecode.iter().enumerate() {
                println!("{:04} : {:?}", ip, instr);
            }
        }
        Commands::Run { file } => {
            let source = read_sa_file(file);
            let bytecode = compile_source(&source);
            
            println!("--- Running {} on VM ---", file);
            let mut vm = VM::new();
            let result = vm.run(&bytecode);
            println!("\nVM Execution Yield/Result: {}", result);
        }
    }
}

/// Helper function to validate file extension and read content
fn read_sa_file(file_path: &str) -> String {
    let path = Path::new(file_path);
    
    // Enforce your language's extension checking!
    if path.extension().and_then(|s| s.to_str()) != Some("sa") {
        eprintln!("Error: Your compiler only compiles files ending in '.sa'");
        std::process::exit(1);
    }

    match fs::read_to_string(path) {
        Ok(content) => content,
        Err(err) => {
            eprintln!("Error reading file '{}': {}", file_path, err);
            std::process::exit(1);
        }
    }
}

/// Helper pipeline to pass text to our compiler modules
fn compile_source(source: &str) -> Vec<tokens::Instruction> {
    let lexer = Lexer::new(source);
    let mut parser = Parser::new(lexer);
    let ast = parser.parser();
    
    let mut compiler = Compiler::new();
    compiler.compile(&ast);
    compiler.bytecode
}