name: Go CI

on:
  push:
    branches: [main]
    paths:
      - "GoWork/**"

  pull_request:
    branches: [main]
    paths:
      - "GoWork/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Go

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download dependencies
        run: go mod tidy

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
