name: Go CI

on:
  push:
    branches: [main]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download dependencies
        run: go mod tidy

      - name: Build project
        run: go build ./...

      - name: Run tests
        run: go test ./...